// For seeding the database
const urls = [
  'https://www.epicurious.com/recipes/food/views/chickpea-potato-chaat',
  'https://www.epicurious.com/recipes/food/views/peach-cobbler-hot-water',
  'https://www.epicurious.com/recipes/food/views/pasta-with-15-minute-burst-cherry-tomato-sauce-56390060',
  'https://www.epicurious.com/recipes/food/views/gado-gado-mixed-vegetable-salad-indonesian-peanut-sauce',
  'https://www.epicurious.com/recipes/food/views/grilled-jerk-tofu-plantains-mango-salsa-vegan',
  'https://www.epicurious.com/recipes/food/views/honey-mustard-sheet-pan-chicken-dinner-with-potatoes-and-greens',
  'https://www.epicurious.com/recipes/food/views/crispy-chicken-turmeric-lemon-cabbage-peas',
  'https://www.epicurious.com/recipes/food/views/seared-scallops-with-brown-butter-and-lemon-pan-sauce',
  'https://www.epicurious.com/recipes/food/views/one-pan-chicken-drumsticks-with-rice-and-beans',
  'https://www.epicurious.com/recipes/food/views/quick-potato-gnocchi-joy-of-cooking',
  'https://www.epicurious.com/recipes/food/views/summer-pizza-with-salami-zucchini-and-tomatoes',
  'https://www.epicurious.com/recipes/food/views/tamarind-glazed-grilled-chicken-wings',
  'https://www.epicurious.com/recipes/food/views/spicy-lobster-pasta-51241830',
  'https://www.epicurious.com/recipes/food/views/grilled-salmon-peach-curry-coconut-cream-gourdet',
  'https://www.epicurious.com/recipes/food/views/fried-garlic-noodles-sheldon-simeon',
  'https://www.epicurious.com/recipes/food/views/grilled-steak-with-peas-and-eggplant-over-whipped-ricotta',
  'https://www.epicurious.com/recipes/food/views/insanity-burger-56389604',
  'https://www.epicurious.com/recipes/food/views/garlicky-instant-ramen-noodle-salad-grilled-chicken-thighs',
  'https://www.epicurious.com/recipes/food/views/seared-scallops-with-mint-peas-and-bacon',
  'https://www.epicurious.com/recipes/food/views/slow-cooker-green-chicken-chili',
  'https://www.epicurious.com/recipes/food/views/winter-salad-hummus-bowls',
  'https://www.epicurious.com/recipes/food/views/spicy-braised-tofu',
  'https://www.epicurious.com/recipes/food/views/pantry-pasta-puttanesca',
  'https://www.epicurious.com/recipes/food/views/cauliflower-carbonara',
  'https://www.epicurious.com/recipes/food/views/gingery-chicken-soup-with-zucchini-noodles',
  'https://www.epicurious.com/recipes/food/views/stuffed-sweet-potatoes-with-curried-chickpeas-and-mushrooms',
  'https://www.epicurious.com/recipes/food/views/easy-yogurt-and-spice-roasted-salmon-sabrina-ghayour',
  'https://www.epicurious.com/recipes/food/views/rice-cake-mixed-vegetables-hsiao-ching-chou',
  'https://www.epicurious.com/recipes/food/views/ros-omelette-chaat',
  'https://www.epicurious.com/recipes/food/views/oven-risotto-with-crispy-roasted-mushrooms',
];

module.exports = urls;
