// For seeding the database
const recipes = [
  {
    time: {
      prep: '',
      cook: '',
      active: '35 minutes',
      inactive: '',
      ready: '',
      total: '2 hours',
    },
    ingredients: [
      '2 14-oz. blocks extra-firm tofu, drained',
      '2 small red onions, coarsely chopped',
      '10 scallions, cut into 2" pieces',
      '12 garlic cloves',
      '4–6 Scotch bonnet or habanero chiles, seeds removed, or 1–2 tsp. Scotch bonnet chile powder',
      '12 sprigs thyme, leaves picked',
      '2 1" pieces ginger, peeled',
      '16–20 allspice berries or 2 Tbsp. ground allspice',
      '⅔ cup soy sauce',
      '½ cup (packed) dark brown sugar',
      '½ cup distilled white vinegar',
      '¼ cup fresh lime juice',
      '1 Tbsp. plus 1 tsp. browning sauce (preferably Grace; optional)',
      '1 Tbsp. freshly ground black pepper',
      '2 tsp. Diamond Crystal or 1¼ tsp. Morton kosher salt',
      '½ tsp. freshly grated nutmeg',
      '½ tsp. ground cinnamon',
      '¼ cup avocado oil or vegetable oil',
      'Juice of 1 lime',
      '1 Scotch bonnet chile or jalapeño, seeds removed',
      '2 cups coarsely chopped ripe mango',
      '⅔ cup coarsely chopped red bell pepper',
      '½ cup coarsely chopped red onion',
      '2 Tbsp. coarsely chopped cilantro',
      '2 tsp. agave nectar or honey (optional)',
      '½ tsp. Diamond Crystal or ¼ tsp. Morton kosher salt, plus more',
      '¼ cup avocado oil or vegetable oil, plus more for grill',
      '⅔ cup (packed) dark brown sugar',
      '¼ cup distilled white vinegar',
      '1 tsp. Diamond Crystal or ½ tsp. Morton kosher salt',
      '1 tsp. freshly ground black pepper',
      '4 very ripe (almost black) plantains, halved lengthwise',
      'Thinly sliced scallions and lime wedges (for serving)',
    ],
    instructions: [
      'Wrap tofu in 2 layers of paper towel, place on a rimmed baking sheet, and weigh down with something heavy (large cans or a small cast-iron skillet work well). Let sit 30 minutes. (Alternatively, press tofu in a tofu press 15–30 minutes.)',
      'Meanwhile, process red onions, scallions, garlic, chiles, thyme, ginger, allspice, soy sauce, brown sugar, vinegar, lime juice, browning sauce (if using), black pepper, salt, nutmeg, and cinnamon in a food processor or blender to a coarse purée. With motor running, stream in oil and process to a fine purée. Transfer jerk sauce to a bowl.',
      'Unwrap tofu and cut each block crosswise into 6 slices. Pour 1 cup jerk sauce into a baking dish, then add tofu slices and turn to coat. Set remaining jerk sauce aside for brushing and serving. Cover and chill tofu at least 30 minutes and up to 1 day.\nDo ahead: Jerk sauce can be made 3 weeks ahead. Cover and chill.',
      'Pulse lime juice, chile, mango, bell pepper, red onion, cilantro, agave (if using),and ½ tsp. Diamond Crystal or ¼ tsp. Morton kosher salt in a food processor just until coarsely chopped, 5–10 pulses. Taste salsa and season with more salt if needed. Transfer to a bowl; cover and chill until ready to serve.',
      'Prepare a grill for medium-high heat; lightly oil grate. Arrange tofu on grate, cover, and grill, brushing with reserved jerk sauce as you turn tofu, until lightly browned and grill marks appear, about 5 minutes per side. Transfer to a plate and brush with additional sauce, if desired.',
      'Meanwhile, mix brown sugar, vinegar, salt, pepper, and remaining ¼ cup oil in a small bowl. Brush cut sides of plantains generously with mixture.',
      'Arrange plantains, cut side down, on grate, cover, and grill, brushing all over with brown sugar mixture as you turn, until deep golden and grill marks appear, about 7 minutes per side. Transfer plantains to plates with tofu.',
      'Top tofu and plantains with scallions and serve with salsa and lime wedges.',
    ],
    tags: [
      'Tofu',
      'Onion',
      'Green Onion/Scallion',
      'Garlic',
      'Chile Pepper',
      'Thyme',
      'Ginger',
      'Soy Sauce',
      'Vinegar',
      'Lime Juice',
      'Pepper',
      'Nutmeg',
      'Cinnamon',
      'Lime',
      'Mango',
      'Bell Pepper',
      'Cilantro',
      'Honey',
      'Plantain',
      'Dinner',
      'Lunch',
      'Vegan',
      'Vegetarian',
      'Summer',
      'Grill/Barbecue',
      'Tree Nut Free',
      'Juneteenth',
      'Labor Day',
      'Father\'s Day',
      'Wheat/Gluten-Free',
      'Peanut Free',
      'Jamaica',
    ],
    name: 'Grilled Jerk Tofu and Plantains With Mango Salsa',
    description:
      'I was inspired to create this vegan grilled jerk tofu recipe after visits to Jamaica where I found myself inhaling the aromas of jerk chicken. Try it!',
    servings: '4 Servings',
    image:
      'https://assets.epicurious.com/photos/60db3d7b9e040b1d0fd16a41/2:1/w_1260%2Ch_630/JerkTofu_RECIPE_062321_18633.jpg',
    url: 'https://www.epicurious.com/recipes/food/views/grilled-jerk-tofu-plantains-mango-salsa-vegan',
    createdAt: '2022-10-28T10:42:43.572Z',
    id: '61150f2305fa701172f99b22',
  },
  {
    time: {
      prep: '',
      cook: '',
      active: '15 minutes',
      inactive: '',
      ready: '',
      total: '30 minutes',
    },
    ingredients: [
      '1 lb. baby potatoes',
      'Kosher salt',
      '1 cup tamarind concentrate (such as Cock or Wangderm)',
      '1 Tbsp. sugar',
      '1 tsp. Diamond Crystal or ½ tsp. Morton kosher salt',
      '½ tsp. cayenne pepper',
      '½ tsp. cumin seeds, crushed',
      '1 bunch cilantro, coarsely chopped (stems and leaves)',
      '1 bunch mint, leaves picked, stems discarded',
      'Juice of 2 limes',
      '1 small serrano chile or green Thai chile, stem removed',
      '1 tsp. cumin seeds',
      '1 tsp. Diamond Crystal or ½ tsp. Morton kosher salt',
      'Juice of ½ lime',
      '1 cup plain whole-milk yogurt',
      '2 Tbsp. sugar',
      '½ tsp. Diamond Crystal or ¼ tsp. Morton kosher salt',
      '2 (15-oz.) cans chickpeas, rinsed',
      '1 large serrano chile, thinly sliced',
      '1 large tomato, finely chopped',
      '1 medium red onion, thinly sliced',
      '¼ cup coarsely chopped cilantro, plus sprigs for serving',
      '2 tsp. chaat masala, plus more for serving',
      'Sev (such as Garvi Gujarat, for serving)',
    ],
    instructions: [
      'Place potatoes in a medium pot and pour in cold water to cover by 1"; season generously with salt. Bring to a boil, reduce heat to medium, and cook until potatoes are fork-tender, 15–18 minutes. Drain and let cool slightly, then halve potatoes. Transfer to a large bowl and chill until ready to use.',
      'Whisk tamarind concentrate, sugar, salt, cayenne, and cumin seeds in another small bowl until combined and sugar is dissolved.',
      'Purée cilantro, mint, lime juice, chile, cumin seeds, salt, and ¼ cup water in a blender until smooth.',
      'Whisk lime juice, yogurt, sugar, and salt in a small bowl until combined and sugar is dissolved.',
      'Add chickpeas, half of chile, ½ cup tomato, ½ cup red onion, ¼ cup cilantro, 2 tsp. chaat masala, ½ cup yogurt mixture, ½ cup tamarind chutney, and ½ cup green chutney to potatoes and toss to combine.',
      'Transfer chaat to a platter and drizzle 2 Tbsp. yogurt mixture, 2 Tbsp. tamarind chutney, and 2 Tbsp. green chutney over. Sprinkle with a pinch of chaat masala and top with sev and remaining chile, tomato, and red onion as desired. Scatter a few cilantro sprigs on top and serve with remaining yogurt and chutneys alongside.',
    ],
    tags: [
      'Potato',
      'Tamarind',
      'Cumin',
      'Cilantro',
      'Mint',
      'Lime Juice',
      'Chile Pepper',
      'Yogurt',
      'Chickpea',
      'Tomato',
      'Onion',
      'Side',
      'Summer',
      'Vegetarian',
      'Appetizer',
      'Dinner',
      'Diwali',
      'snack',
    ],
    name: 'Chickpea-Potato Chaat',
    description:
      'Chaat is the perfect low-cook recipe for hot days. Canned chickpeas and simmered potatoes with cilantro-mint chutney, tamarind chutney, & yogurt.',
    servings: '6 Servings',
    image:
      'https://assets.epicurious.com/photos/60f09a34ae9cc866a51a25d0/2:1/w_1260%2Ch_630/ChickpeaPotatoChaat_RECIPE_071321_19121.jpg',
    url: 'https://www.epicurious.com/recipes/food/views/chickpea-potato-chaat',
    createdAt: '2022-10-28T10:42:43.573Z',
    id: '61150f2505fa701172f99b2c',
  },
  {
    time: {
      prep: '',
      cook: '',
      active: '25 minutes',
      inactive: '',
      ready: '',
      total: '40 minutes',
    },
    ingredients: [
      '2 (15-ounce) cans chickpeas, drained, rinsed, patted dry',
      '8 ounces button mushrooms, quartered (about 3 1/2 cups)',
      '2 teaspoons curry powder',
      '1/2 teaspoon ground cumin',
      '5 tablespoons olive oil, divided',
      '1 1/2 teaspoons kosher salt, divided',
      '4 medium sweet potatoes (about 9 ounces each)',
      '5 ounces baby spinach (about 4 packed cups)',
      '2 limes',
      '1/2 cup Greek-style plain full- or low-fat yogurt',
      '1/2 cup coarsely chopped cilantro, plus whole leaves for serving',
    ],
    instructions: [
      'Preheat oven to 450°F. Toss chickpeas, mushrooms, curry powder, cumin, 2 Tbsp. oil, and 3/4 tsp. salt on a rimmed baking sheet. Divide mushrooms and chickpeas into separate piles and spread in a single layer.',
      'Cut potatoes in half lengthwise. Rub with 1 Tbsp. oil and 1/2 tsp. salt and transfer cut side down to another rimmed baking sheet.',
      'Roast vegetables and potatoes, rotating pans halfway through and arranging spinach over vegetables during the last 2 minutes of cooking, until chickpeas are golden brown and crisp and potatoes are fork-tender, about 25 minutes.',
      'Meanwhile, juice limes to yield 6 Tbsp. juice. Blend yogurt, 4 Tbsp. lime juice, and 1/2 cup chopped cilantro in a blender until smooth.',
      'Transfer spinach, mushrooms, and chickpeas to separate bowls. Transfer potatoes to a serving platter. Using the back of a spoon, gently push down in center of potato halves to create a divot.',
      'Spoon vegetables into divots, then top with yogurt sauce and cilantro leaves.',
      'Potatoes, chickpeas, and mushrooms can be cooked 3 days ahead; store separately, cover, and chill. Reheat in oven before serving.',
    ],
    tags: [
      'Back to School',
      'Dinner',
      'Vegetarian',
      'Sweet Potato/Yam',
      'Chickpea',
      'Mushroom',
      'Curry',
      'Spinach',
      'Yogurt',
      'Lime',
      'Cilantro',
      'Small Plates',
    ],
    name: 'Stuffed Sweet Potatoes with Curried Chickpeas and Mushrooms',
    description:
      'This easy, Indian-inspired vegetarian dinner stars baked sweet potatoes loaded with curry-spiced chickpeas, mushrooms, and spinach. Roast the sweet potatoes ahead of time to get dinner on the table even faster.',
    servings: '4 servings',
    image:
      'https://assets.epicurious.com/photos/59aececa389c09538cc56420/2:1/w_1260%2Ch_630/Stuffed-Sweet-Potatoes-with-Curry-Chickpea-Back-to-School-Grocery-Bag-768-14082017.jpg',
    url: 'https://www.epicurious.com/recipes/food/views/stuffed-sweet-potatoes-with-curried-chickpeas-and-mushrooms',
    createdAt: '2022-10-28T10:42:43.573Z',
    id: '61150f2905fa701172f99b4a',
  },
  {
    time: {
      prep: '',
      cook: '',
      active: '',
      inactive: '',
      ready: '',
      total: '',
    },
    ingredients: [
      '2 cups sliced rice cake',
      '3 cups hot tap water or water that’s been microwaved for 30 seconds',
      '1 tablespoon vegetable oil',
      '2 cups leafy greens, such as baby bok choy, yu choy (cut into ½-inch pieces), or baby spinach leaves',
      '4 medium dried shiitake mushrooms, soaked in hot water for 30 minutes to reconstitute and cut into (¼-inch-thick) pieces',
      '½ cup sliced carrots (⅛ inch thick)',
      '½ cup bean sprouts',
      '1½ tablespoons soy sauce',
      '1 tablespoon black bean garlic sauce',
      '¼ teaspoon sesame oil',
    ],
    instructions: [
      'In a medium bowl, soak the rice cake in the hot water for 2 to 3 minutes, then drain all but about ½ cup water. Set aside.',
      'Preheat a wok over high heat until wisps of smoke rise from the surface. Swirl in the vegetable oil and let heat for a few seconds until it starts to shimmer. Add the greens and stir-fry for about 15 seconds. Add the mushrooms, carrots, and bean sprouts. Stir to combine. Add the rice cake and the reserved water, soy sauce, and black bean garlic sauce. Stir-fry for 2 minutes, or until well combined and the rice cake slices have softened. Finish with the sesame oil. Serve while hot.',
    ],
    tags: [
      'Side',
      'Dinner',
      'Lunch',
      'Lunar New Year',
      'Mushroom',
      'Carrot',
      'Bok Choy',
      'Soy Sauce',
      'Spinach',
      'Sesame Oil',
      'Vegetarian',
      'Vegan',
      'Dairy Free',
      'Peanut Free',
      'Tree Nut Free',
      'Stir-Fry',
      'Wok',
    ],
    name: 'Rice Cake With Mixed Vegetables',
    description:
      'Rice cakes are available sliced, marble-shaped, and in batons. Look for them in the refrigerated aisle of Asian grocery stores. There are dried versions, but the refrigerated version is widely available and easier to work with. I like the slices because there’s more surface area for the sauce. You can use any combination of vegetables and seasonings, so feel free to experiment with flavors. Rice cake is also served at Lunar New Year because the Mandarin name nian gao (“sticky cake”) is a homophone for the nian, which means “year,” and gao, which means “tall” or “high.” When you stick those years together, you’re wishing others longevity.',
    servings: 'Makes 4 servings',
    image:
      'https://assets.epicurious.com/photos/6011ddac7e21f30fee735024/2:1/w_1260%2Ch_630/RiceCakeVegetables_RECIPE_012521_540.jpg',
    url: 'https://www.epicurious.com/recipes/food/views/rice-cake-mixed-vegetables-hsiao-ching-chou',
    createdAt: '2022-10-28T10:42:43.573Z',
    id: '61150f2905fa701172f99b54',
  },
  {
    time: {
      prep: '',
      cook: '',
      active: '20 minutes',
      inactive: '',
      ready: '',
      total: '45 minutes',
    },
    ingredients: [
      '2 Tbsp. Dijon mustard',
      '2 Tbsp. plus 2 tsp. honey',
      '1/3 cup plus 3 Tbsp. extra-virgin olive oil, divided',
      '4 whole chicken legs (thigh and drumstick; about 2 lb. total), patted dry',
      '2 1/2 tsp. kosher salt, divided',
      '1 tsp. freshly ground black pepper, divided',
      '1 1/2 lb. baby Yukon Gold potatoes, halved',
      '4 rosemary sprigs',
      '1 garlic clove, finely grated',
      '3 Tbsp. fresh lemon juice',
      '4 tsp. whole grain mustard',
      '1 small head of frisée or 1/2 small head of escarole, trimmed, torn into bite-size pieces',
      '1/2 cup parsley leaves',
    ],
    instructions: [
      'Place a rack in top third of oven; preheat to 375°F. Whisk Dijon mustard, 2 Tbsp. honey, and 1 Tbsp. oil in a medium bowl to combine. Season chicken on all sides with 1 tsp. salt and 1/2 tsp. pepper. Transfer to bowl with honey mustard and toss to coat.',
      'Toss potatoes, 2 Tbsp. oil, 1 tsp. salt, and remaining 1/2 tsp. pepper on a rimmed baking sheet. Arrange chicken legs (skin side up) in the center of pan; discard excess marinade. Arrange potatoes around outside of pan in an even layer, then turn cut side down (this will help them brown better). Arrange rosemary over potatoes. Roast until chicken and potatoes are golden brown and an instant-read thermometer inserted into thickest part of chicken registers 165°F, 30–40 minutes.',
      'Whisk garlic, lemon juice, whole grain mustard, and remaining 1/3 cup oil, 2 tsp. honey, and 1/2 tsp. salt in a small bowl. Divide chicken and potatoes among plates, then arrange frisée and parsley alongside potatoes. Drizzle dressing over chicken, potatoes, and frisée.',
      'Do Ahead: Chicken can be marinated 8 hours ahead. Cover and chill.',
    ],
    tags: [
      'Chicken',
      'Mustard',
      'Honey',
      'Olive Oil',
      'Potato',
      'Rosemary',
      'Garlic',
      'Lemon Juice',
      'Lettuce',
      'Salad',
      'Parsley',
      'Dinner',
      'Fall',
      'Winter',
      'One-Pot Meal',
      'Quick & Easy',
      'Wheat/Gluten-Free',
      'Dairy Free',
    ],
    name: 'Double-the-Mustard Chicken With Potatoes and Greens',
    description:
      'Two kinds of mustard make all the difference in this sheet-pan dinner. Dijon mustard mixed with honey serves as a sweet-tart marinade for the chicken, while the whole seeds in old-style mustard add pops of crunch and flavor to the dressing.',
    servings: '4 servings',
    image:
      'https://assets.epicurious.com/photos/5dc7263dd482f10008d4fadb/2:1/w_1260%2Ch_630/HoneyMustardChicken_RECIPE_110519_5882.jpg',
    url: 'https://www.epicurious.com/recipes/food/views/honey-mustard-sheet-pan-chicken-dinner-with-potatoes-and-greens',
    createdAt: '2022-10-28T10:42:43.573Z',
    id: '61150f2405fa701172f99b28',
  },
  {
    time: {
      prep: '',
      cook: '',
      active: '30 minutes',
      inactive: '',
      ready: '',
      total: '30 minutes',
    },
    ingredients: [
      '1 1/2 cups whole-milk ricotta',
      '1 tsp. finely grated lemon zest',
      '5 Tbsp. extra-virgin olive oil, divided, plus more for grill and drizzling',
      '2 3/4 tsp. kosher salt, divided',
      '2 (1"–1 1/2"-thick) boneless strip steaks (about 1 1/2 lb. total), patted dry',
      '1 1/2 tsp. freshly ground black pepper, divided, plus more',
      '2 small eggplants (about 11 oz. total), trimmed, sliced lengthwise into 1" spears',
      '1/2 lb. sugar snap peas, strings removed',
      'Flaky sea salt',
      '1/2 cup mint leaves',
      '1 Fresno chile, thinly sliced (optional)',
      'Lemon wedges (for serving)',
    ],
    instructions: [
      'Whisk ricotta, lemon zest, 3 Tbsp. oil, and 3/4 tsp. kosher salt in a large bowl until smooth and fluffy; set aside.',
      'Prepare a grill for medium-high heat; oil grate. Season steaks on all sides with 1 1/2 tsp. kosher salt and 1 tsp. pepper. Grill steaks until lightly charred and an instant-read thermometer inserted into the thickest part registers 120°F, 5–7 minutes per side for medium-rare. Transfer to a cutting board and let rest 10 minutes before slicing against the grain.',
      'While steak rests, toss eggplant with 2 Tbsp. oil; season with 1/2 tsp. kosher salt and 1/2 tsp. pepper. Grill eggplant, turning often, until skin is lightly charred and flesh is softened, about 5 minutes.',
      'Grill peas in a grill basket or on a wire rack set over grill alongside eggplant, turning often, until lightly charred and softened, about 3 minutes.',
      'Spread reserved ricotta on a platter. Arrange eggplant and peas over. Drizzle with oil; season with sea salt and pepper. Top with mint and chile (if using). Serve with lemon wedges alongside.',
      'Transfer steak to another platter. Drizzle with oil, then season with sea salt and pepper. Serve alongside vegetables.',
    ],
    tags: [
      'Steak',
      'Peanut Free',
      'Ricotta',
      'Lemon',
      'Eggplant',
      'Pea',
      'Sugar Snap Pea',
      'Mint',
      'Chile',
      'Grill',
      'Quick & Easy',
      'Summer',
      'Dinner',
      'Wheat/Gluten-Free',
    ],
    name: 'Grilled Steak With Peas and Eggplant Over Whipped Ricotta',
    description:
      'No pots or pans needed for this easy summertime recipe: The eggplant spears and sugar snap peas are charred side by side on the grill, and they perfectly complement a simple grilled steak. The lemony whipped ricotta provides a creamy brightness to balance out the smoky meat and veg.',
    servings: '4 servings',
    image:
      'https://assets.epicurious.com/photos/5ced8276bc4c065f31b10580/2:1/w_1260%2Ch_630/Grilled-Steak-and-Snap-Peas-with-Ricotta-recipe-22102019.jpg',
    url: 'https://www.epicurious.com/recipes/food/views/grilled-steak-with-peas-and-eggplant-over-whipped-ricotta',
    createdAt: '2022-10-28T10:42:43.574Z',
    id: '61150f2505fa701172f99b34',
  },
  {
    time: {
      prep: '',
      cook: '',
      active: '25 minutes',
      inactive: '',
      ready: '',
      total: '1 hour 10 minutes',
    },
    ingredients: [
      '¾ cup tamarind purée',
      '¼ cup fish sauce',
      '2 Tbsp. light or dark brown sugar',
      '1 Tbsp. crushed red pepper flakes',
      '1 tsp. ground cumin',
      '3 tsp. Diamond Crystal or 1½ tsp. Morton kosher salt, divided',
      '4 lb. chicken wings, drumettes and flats separated if desired',
      '¼ small red onion, very thinly sliced, preferably on a mandoline',
      'Cilantro leaves with tender stems and lime wedges (for serving)',
    ],
    instructions: [
      'Whisk tamarind purée, fish sauce, brown sugar, red pepper flakes, cumin, and 1 tsp. Diamond Crystal or ½ tsp. Morton kosher salt in a medium bowl until combined and a loose paste forms. Set tamarind glaze aside.',
      'Pat wings dry with paper towels, then season all over with remaining 2 tsp. Diamond Crystal or 1 tsp. Morton kosher salt. Place in a large bowl; add half of tamarind glaze and toss to coat. Chill 15 minutes. Set remaining glaze aside.',
      'Meanwhile, place onion in a bowl of ice water and set aside.',
      'Prepare a grill for medium indirect heat (for a charcoal grill, bank coals on one side of grill; for a gas grill, leave one or two burners off). Arrange wings on grate over indirect heat, making sure not to overcrowd. Brush top of each wing with some reserved glaze. Cover and grill 15 minutes. Uncover, turn wings over, and brush other side with glaze. Re-cover and grill until wings are golden brown and a thermometer inserted into the thickest part of a wing registers 165°F, about 15 minutes.',
      'Brush wings with more glaze, then move over direct heat and grill until charred in spots, 1–2 minutes per side.',
      'Transfer wings to a platter. Drain onion and place on paper towels; pat dry. Scatter onion over wings and top with cilantro. Serve with lime wedges for squeezing over.',
    ],
    tags: [
      'Chicken',
      'Tamarind',
      'Cumin',
      'Onion',
      'Cilantro',
      'Summer',
      'Wheat/Gluten-Free',
      'Tree Nut Free',
      'Grill/Barbecue',
      'snack',
      'Appetizer',
      'Side',
      'Lunch',
      'Dinner',
      'Backyard BBQ',
      'Picnic',
      'Peanut Free',
      'Dairy Free',
      'Quick & Easy',
    ],
    name: 'Spicy Tamarind-Glazed Grilled Chicken Wings',
    description:
      'These grilled chicken wings are marinated in tamarind purée, fish sauce, brown sugar, red pepper flakes, and cumin, with more brushed on as they grill.',
    servings: '4 servings',
    image:
      'https://assets.epicurious.com/photos/609acf9ed10d31ed8e8913a4/2:1/w_1260%2Ch_630/TamarindWings_RECIPE_050621_14827.jpg',
    url: 'https://www.epicurious.com/recipes/food/views/tamarind-glazed-grilled-chicken-wings',
    createdAt: '2022-10-28T10:42:43.574Z',
    id: '61150f2605fa701172f99b3e',
  },
  {
    time: {
      prep: '',
      cook: '',
      active: '30 minutes',
      inactive: '',
      ready: '',
      total: '35 minutes',
    },
    ingredients: [
      '1 lb. linguine or other long pasta',
      'Kosher salt',
      '1 (14-oz.) can diced tomatoes',
      '1/2 cup extra-virgin olive oil, divided',
      '1/4 cup capers, drained',
      '6 oil-packed anchovy fillets',
      '1 Tbsp. tomato paste',
      '1/3 cup pitted Kalamata olives, halved',
      '2 tsp. dried oregano',
      '1/2 tsp. crushed red pepper flakes',
      '6 oz. oil-packed tuna',
    ],
    instructions: [
      'Cook pasta in a large pot of boiling salted water, stirring occasionally, until al dente. Drain pasta, reserving 1 cup pasta cooking liquid; return pasta to pot.',
      'While pasta cooks, pour tomatoes into a fine-mesh sieve set over a medium bowl. Shake to release as much juice as possible, then let tomatoes drain in sieve, collecting juices in bowl, until ready to use.',
      'Heat 1/4 cup oil in a large deep-sided skillet over medium-high. Add capers and cook, swirling pan occasionally, until they burst and are crisp, about 3 minutes. Using a slotted spoon, transfer capers to a paper towel–lined plate, reserving oil in skillet.',
      'Combine anchovies, tomato paste, and drained tomatoes in skillet. Cook over medium-high heat, stirring occasionally, until tomatoes begin to caramelize and anchovies start to break down, about 5 minutes. Add collected tomato juices, olives, oregano, and red pepper flakes and bring to a simmer. Cook, stirring occasionally, until sauce is slightly thickened, about 5 minutes. Add pasta, remaining 1/4 cup oil, and 3/4 cup pasta cooking liquid to pan. Cook over medium heat, stirring and adding remaining 1/4 cup pasta cooking liquid to loosen if needed, until sauce is thickened and emulsified, about 2 minutes. Flake tuna into pasta and toss to combine.',
      'Divide pasta among plates. Top with fried capers.',
    ],
    tags: ['Pasta', 'Tomato', 'Capers', 'Anchovy', 'Olive', 'Oregano', 'Tuna'],
    name: 'Pantry Pasta Puttanesca',
    description:
      'Keep these ingredients stocked in your pantry, and a briny, flavor-packed, classic Italian pasta will always be a dinner option.',
    servings: '4 servings',
    image:
      'https://assets.epicurious.com/photos/5ac2492da0f0d86fa2879ce5/2:1/w_1260%2Ch_630/Google-Express-Pasta-Puttanesca-recipe-23012018.jpg',
    url: 'https://www.epicurious.com/recipes/food/views/pantry-pasta-puttanesca',
    createdAt: '2022-10-28T10:42:43.574Z',
    id: '61150f2605fa701172f99b42',
  },
  {
    time: {
      prep: '',
      cook: '',
      active: '',
      inactive: '',
      ready: '',
      total: '',
    },
    ingredients: [
      '500g skinless salmon fillet, cut into 4cm cubes',
      '4 tablespoons Greek yogurt',
      '1 tablespoon garlic granules',
      '1 heaped tablespoon rose harissa',
      '1 teaspoon ground turmeric',
      '1 teaspoon paprika',
      'Finely grated zest of 1 unwaxed lime and a good squeeze of juice',
      '1 teaspoon olive oil',
      'Generous amount of Maldon sea salt flakes and freshly ground black pepper',
      'Tortilla wraps',
      'Sliced tomatoes',
      'Finely sliced onion',
      'Coriander leaves',
      'Greek yogurt',
    ],
    instructions: [
      'Preheat your oven to its highest setting (with fan if it has one). Line a baking tray with baking paper.',
      'Mix all the marinade ingredients together in a mixing bowl. Add the salmon and turn until well coated in the marinade.',
      'Spread the salmon out on the prepared baking tray and roast for 10 minutes until cooked through. Remove from the oven and serve immediately with tortilla wraps, tomatoes, finely sliced onion, coriander leaves and Greek yogurt.',
    ],
    tags: [
      'Salmon',
      'Fish',
      'Seafood',
      'Quick & Easy',
      'Pescatarian',
      'Wheat/Gluten-Free',
    ],
    name: 'Yogurt and Spice Roasted Salmon',
    description:
      'This method of roasting salmon cubes at a high temperature ensures you get a little charring on the outside yet perfectly cooked salmon on the inside.',
    servings: '4 servings',
    image:
      'https://assets.epicurious.com/photos/5f5fef04de70825418a829f7/2:1/w_1260%2Ch_630/CharredSalmon_RECIPE_091020_11608_VOG_final.jpg',
    url: 'https://www.epicurious.com/recipes/food/views/easy-yogurt-and-spice-roasted-salmon-sabrina-ghayour',
    createdAt: '2022-10-28T10:42:43.574Z',
    id: '61150f2705fa701172f99b46',
  },
  {
    time: {
      prep: '',
      cook: '',
      active: '',
      inactive: '',
      ready: '',
      total: '30 minutes',
    },
    ingredients: [
      '1 tablespoon coconut oil',
      '1 small yellow onion, finely chopped',
      '1 medium tomato, coarsely chopped',
      '1 tablespoon store-bought ginger-garlic paste',
      '1 teaspoon ground turmeric',
      '½ teaspoon Kashmiri or other red chile powder',
      '1 tablespoon store-bought coconut paste',
      '1 teaspoon garam masala',
      'Kosher salt',
      '10 large eggs',
      '1 teaspoon Kashmiri or other red chile powder',
      'Kosher salt',
      '2 tablespoons vegetable oil or coconut oil',
      '1 medium yellow onion, finely chopped',
      '2 green chiles, finely chopped',
      'Lime wedges, for serving',
      'Finely chopped onion, for serving',
    ],
    instructions: [
      'In a medium sauté pan, heat the oil over medium-high heat until glistening, about 2 minutes. Add the onion and sauté until translucent, about 5 minutes. Add the tomato, ginger-garlic paste, turmeric, and chile powder and sauté, stirring occasionally, until the tomatoes begin to break apart, about 5 minutes longer. Stir in the coconut paste and garam masala and cook until everything is well incorporated and the smell of coconut perfumes the air, about 5 more minutes. Add a little water, if needed, to achieve a loose gravy texture. Season with salt and set aside.',
      'In a large bowl, whisk together the eggs and season with the chile powder and salt. In a sauté pan, heat the oil over medium-high heat and sauté the onion and chile peppers, stirring occasionally, until the onions are translucent, about 5 minutes. Reduce the heat to medium and pour the eggs into the pan. Rotate the pan in a circle as the omelet cooks to ensure even distribution of the eggs. Once the center of the omelet is just set, 4 to 6 minutes, flip the omelet onto itself to form a half-moon shape. Season with salt, transfer to a plate, and spoon the warm ros on top. Garnish with a lime wedge and raw onions.',
    ],
    tags: ['Omelet', 'Egg', 'Vegetarian', 'Breakfast', 'Dinner', 'Lunch'],
    name: 'Ros Omelette',
    description:
      'Make this Goan omelet, with its rich and comforting, fiery gravy, for breakfast, lunch, or dinner. It\'s the ideal dinner for one.',
    servings: '4 servings',
    image:
      'https://assets.epicurious.com/photos/601db1396f4da5d34165cba8/2:1/w_1260%2Ch_630/Ros%20omlette_Page_1_Image_0001.jpg',
    url: 'https://www.epicurious.com/recipes/food/views/ros-omelette-chaat',
    createdAt: '2022-10-28T10:42:43.575Z',
    id: '61150f2a05fa701172f99b56',
  },
];

module.exports = recipes;
