GET http://localhost:3001/api/favoriteRecipes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjoiNjM0MmM0MWRjZmQzOGEwZjNhNDM4NjcwIiwiaWF0IjoxNjY1MzIxNDIxfQ.Ijuz4cSHL0OFa-b94f4jk4sDdNTy1BTLUp8Kl41czpA
